/// <reference types="next" />
/// <reference types="next/image-types/global" />

// NOTE: This file should not be edited. It is auto-generated by `next dev`
// and `next build`; it's included here only so the project type-checks
// before the first `next dev` run.
